### ISSUE TITLE
Switch between apps without loading info

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MscrmTools.SiteMapEditor#11]
Hi
is there a way to give the ability to switch between the apps without loading all entity information and web resources again

**Comment by MscrmTools** [comment]
I can work on this

Thank you for the suggestion

**Comment by aboodh95** [comment]
Thank You

**Comment by MscrmTools** [comment]
I reopen the issue to remember I have some work to do

**Comment by aboodh95** [comment]
Ok
