### ISSUE TITLE
Portal page links to wrong Github project

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/MscrmTools.SiteMapEditor#14]
This is probably not the right place to report this, but the Toolbox portal page for this plugin: https://www.xrmtoolbox.com/plugins/MsCrmTools.SiteMapEditor/ 
points to the Web Resources Manager project:
https://github.com/MscrmTools/MsCrmTools.WebResourcesManager

**Comment by MscrmTools** [comment]
Thank you for reporting it! Fixing it right now

**Comment by bwmodular** [comment]
All good now - thanks for fixing!
