### ISSUE TITLE
XTB crash when closing sitemap editor tab

### ISSUE THREAD

**Issue by bwmodular** [MscrmTools/MscrmTools.SiteMapEditor#15]
The toolbox crashes every time I close the sitemap editor tab after deploying sitemap changes.
Toolbox Version 1.2018.3.21
Editor Version 1.2017.4.10

Repro steps:
Open Toolbox
Connect to CRM
Open sitemap editor
Load Sitemap
Make a change (ie add new subarea)
Click Update Sitemap - wait until sitemap deployed
Click on the Close Tab button (X). When prompted 'Are you sure you want to close this tab?', click Yes.
You see this dialogue box, even if you have no unsaved changes:

![image](https://user-images.githubusercontent.com/1889586/38730121-47811564-3f0d-11e8-9dd5-6aed1737241f.png)

No matter whether you select Yes or No, XTB will crash - Toolbar says 'Not Responding', cursor turns to spinny circle. Forced to hard close the program.

**Comment by bwmodular** [comment]
This doesn't just happen when I close the sitemap editor tab, it also happens when I close XTB and have been using the sitemap editor.

**Comment by lar-mar** [comment]
I also experience this behavior for months. I always need to end XTB via taskmanager.
