### ISSUE TITLE
SiteMap Editor for latest Dynamics 365

### ISSUE THREAD

**Issue by daniel-fraubaum** [MscrmTools/MscrmTools.SiteMapEditor#19]
SiteMap Editor for latest Dynamics 365 please! :-)
If I want to load the default SiteMap, the latest one is V8.2 but Dynamics 365 Online already has the version 9.x

**Comment by MscrmTools** [comment]
Closing the issue as it has been transfered in the appropriate repository

**Comment by daniel-fraubaum** [comment]
So any News when SiteMap Editor will get an update?

**Comment by MscrmTools** [comment]
I’m in holidays right now so not very soon.

**Comment by daniel-fraubaum** [comment]
Ok 😊 Have a nice Holiday!

Cheers,
Daniel


Von: MscrmTools <notifications@github.com>
Gesendet: Mittwoch, 10. April 2019 17:05
An: MscrmTools/MscrmTools.SiteMapEditor <MscrmTools.SiteMapEditor@noreply.github.com>
Cc: Fraubaum Daniel <daniel@fraubaum.at>; Author <author@noreply.github.com>
Betreff: Re: [MscrmTools/MscrmTools.SiteMapEditor] SiteMap Editor for latest Dynamics 365 (#19)


I’m in holidays right now so not very soon.

**Comment by daniel-fraubaum** [comment]
Are you still on holidays? 😊

Von: MscrmTools <notifications@github.com>
Gesendet: Mittwoch, 10. April 2019 17:05
An: MscrmTools/MscrmTools.SiteMapEditor <MscrmTools.SiteMapEditor@noreply.github.com>
Cc: Fraubaum Daniel <daniel@fraubaum.at>; Author <author@noreply.github.com>
Betreff: Re: [MscrmTools/MscrmTools.SiteMapEditor] SiteMap Editor for latest Dynamics 365 (#19)


I’m in holidays right now so not very soon.

**Comment by daniel-fraubaum** [comment]
Any news? 😊

Von: Fraubaum Daniel
Gesendet: Mittwoch, 8. Mai 2019 16:45
An: MscrmTools/MscrmTools.SiteMapEditor <reply@reply.github.com>; MscrmTools/MscrmTools.SiteMapEditor <MscrmTools.SiteMapEditor@noreply.github.com>
Cc: Author <author@noreply.github.com>
Betreff: AW: [MscrmTools/MscrmTools.SiteMapEditor] SiteMap Editor for latest Dynamics 365 (#19)

Are you still on holidays? 😊

Von: MscrmTools <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Mittwoch, 10. April 2019 17:05
An: MscrmTools/MscrmTools.SiteMapEditor <MscrmTools.SiteMapEditor@noreply.github.com<mailto:MscrmTools.SiteMapEditor@noreply.github.com>>
Cc: Fraubaum Daniel <daniel@fraubaum.at<mailto:daniel@fraubaum.at>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [MscrmTools/MscrmTools.SiteMapEditor] SiteMap Editor for latest Dynamics 365 (#19)


I’m in holidays right now so not very soon.

**Comment by MscrmTools** [comment]
Hi,
I just installed a v9 onPremise to get the default sitemap.
Problem with Online is it changes almost every month and not everybody has all features activated...
