### ISSUE TITLE
Unhandled exception with site map editor 1.2016.12.2

### ISSUE THREAD

**Issue by anothersphere** [MscrmTools/MscrmTools.SiteMapEditor#3]
When I try to Load SiteMap, I get an unhandled exception (xrmt version 1.2016.5.27)

This was not happening in the previous build.
Occurs over multiple CRM instances.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MsCrmTools.SiteMapEditor.SiteMapEditor.DisplaySiteMap()
   at MsCrmTools.SiteMapEditor.SiteMapEditor.<LoadSiteMap>b__35_1(RunWorkerCompletedEventArgs e)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2016.5.27
    Win32 Version: 1.2016.5.27
    CodeBase: file:///D:/XRM%20Toolbox/XrmToolBox.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2016.5.27
    Win32 Version: 1.2016.5.27
    CodeBase: file:///D:/XRM%20Toolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 10.0.14393.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2016.5.27
    Win32 Version: 1.2016.5.27
    CodeBase: file:///D:/XRM%20Toolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2016.5.27
    Win32 Version: 1.2016.5.27
    CodeBase: file:///D:/XRM%20Toolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 8.0.0.0
    Win32 Version: 8.1.0.383
    CodeBase: file:///D:/XRM%20Toolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AccessTeamImportTool
    Assembly Version: 1.2016.12.18
    Win32 Version: 1.2016.12.18
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/ACCESSTEAMIMPORTTOOL.DLL
----------------------------------------
ACL.XrmToolBox.BulkRecordAssigner
    Assembly Version: 1.2016.9.10
    Win32 Version: 1.2016.9.10
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/ACL.XRMTOOLBOX.BULKRECORDASSIGNER.DLL
----------------------------------------
AndyPopkin.BulkWorkflowExecution
    Assembly Version: 1.2016.6.7
    Win32 Version: 1.2016.6.7
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/ANDYPOPKIN.BULKWORKFLOWEXECUTION.DLL
----------------------------------------
BDK.XrmToolBox.RecycleBin
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/BDK.XRMTOOLBOX.RECYCLEBIN.DLL
----------------------------------------
BDK.XrmToolBox.StorageCleaner
    Assembly Version: 1.2016.11.3
    Win32 Version: 1.2016.11.3
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/BDK.XRMTOOLBOX.STORAGECLEANER.DLL
----------------------------------------
BDK.XrmToolBox.UserAuditViewer
    Assembly Version: 1.2016.11.3
    Win32 Version: 1.2016.11.3
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/BDK.XRMTOOLBOX.USERAUDITVIEWER.DLL
----------------------------------------
Cinteros.Xrm.CRMWinForm
    Assembly Version: 2016.8.8.9
    Win32 Version: 2016.8.08.9
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XRM.CRMWINFORM.DLL
----------------------------------------
Cinteros.Xrm.FetchXmlBuilder
    Assembly Version: 1.2016.12.115
    Win32 Version: 1.2016.12.115
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XRM.FETCHXMLBUILDER.DLL
----------------------------------------
Cinteros.Xrm.Plugins
    Assembly Version: 1.2016.6.45
    Win32 Version: 1.2016.6.45
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XRM.PLUGINS.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2016.12.115
    Win32 Version: 1.2016.12.115
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
Cinteros.XTB.BulkDataUpdater
    Assembly Version: 1.2016.6.10
    Win32 Version: 1.2016.6.10
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XTB.BULKDATAUPDATER.DLL
----------------------------------------
Cinteros.XTB.PluginTraceViewer
    Assembly Version: 1.2016.12.20
    Win32 Version: 1.2016.12.20
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XTB.PLUGINTRACEVIEWER.DLL
----------------------------------------
Cinteros.XTB.ViewDesigner
    Assembly Version: 1.2016.8.7
    Win32 Version: 1.2016.8.7
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL
----------------------------------------
Colso.DashboardTransferTool
    Assembly Version: 1.2016.7.9
    Win32 Version: 1.2016.7.9
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/COLSO.DASHBOARDTRANSFERTOOL.DLL
----------------------------------------
Colso.DataTransporter
    Assembly Version: 1.2016.10.2
    Win32 Version: 1.2016.10.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/COLSO.DATATRANSPORTER.DLL
----------------------------------------
Colso.Xrm.AttributeEditor
    Assembly Version: 1.2016.8.1
    Win32 Version: 1.2016.8.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/COLSO.XRM.ATTRIBUTEEDITOR.DLL
----------------------------------------
Colso.Xrm.ChartTransferTool
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/COLSO.XRM.CHARTTRANSFERTOOL.DLL
----------------------------------------
Colso.Xrm.DataTransporter
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/COLSO.XRM.DATATRANSPORTER.DLL
----------------------------------------
Cube.XRMToolBox.RecordCounter
    Assembly Version: 1.2016.8.2
    Win32 Version: 1.2016.8.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/CUBE.XRMTOOLBOX.RECORDCOUNTER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2016.10.3
    Win32 Version: 1.2016.10.3
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2016.6.1
    Win32 Version: 1.2016.6.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly Version: 3.0.24.0
    Win32 Version: 3.0.24.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
DLaB.AttributeManager
    Assembly Version: 1.2016.9.10
    Win32 Version: 1.2016.9.10
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DLAB.ATTRIBUTEMANAGER.DLL
----------------------------------------
DLaB.Common
    Assembly Version: 1.0.1.13
    Win32 Version: 1.0.1.13
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DLAB.COMMON.DLL
----------------------------------------
DLaB.EarlyBoundGenerator
    Assembly Version: 1.2016.9.10
    Win32 Version: 1.2016.9.10
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DLAB.EARLYBOUNDGENERATOR.DLL
----------------------------------------
DLaB.Xrm.2016
    Assembly Version: 1.1.8.7
    Win32 Version: 1.1.8.7
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DLAB.XRM.2016.DLL
----------------------------------------
DLaB.Xrm.Entities
    Assembly Version: 8.1.0.1
    Win32 Version: 8.1.0.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DLAB.XRM.ENTITIES.DLL
----------------------------------------
DLaB.XrmToolboxCommon
    Assembly Version: 1.2016.9.10
    Win32 Version: 1.2016.9.10
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DLAB.XRMTOOLBOXCOMMON.DLL
----------------------------------------
DocumentFormat.OpenXml
    Assembly Version: 2.5.5631.0
    Win32 Version: 2.5.5631.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/DOCUMENTFORMAT.OPENXML.DLL
----------------------------------------
EPPlus
    Assembly Version: 4.0.5.0
    Win32 Version: 4.0.5.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/EPPLUS.DLL
----------------------------------------
GapConsulting.PowerBIOptionSetAssistant
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/GAPCONSULTING.POWERBIOPTIONSETASSISTANT.DLL
----------------------------------------
Innofactor.XTB.DateTimeBehaviorUtility
    Assembly Version: 1.2016.10.2
    Win32 Version: 1.2016.10.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/INNOFACTOR.XTB.DATETIMEBEHAVIORUTILITY.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2016.12.5
    Win32 Version: 1.2016.12.5
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2016.5.1
    Win32 Version: 1.2016.5.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2016.9.3
    Win32 Version: 1.2016.9.3
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2016.8.2
    Win32 Version: 1.2016.8.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2016.11.2
    Win32 Version: 1.2016.11.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2016.10.4
    Win32 Version: 1.2016.10.4
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2016.6.1
    Win32 Version: 1.2016.6.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2016.11.2
    Win32 Version: 1.2016.11.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2016.12.2
    Win32 Version: 1.2016.12.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.SynchronousEventOrderEditor
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.SYNCHRONOUSEVENTORDEREDITOR.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2016.4.27
    Win32 Version: 1.2016.4.27
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2016.9.2
    Win32 Version: 1.2016.9.2
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MsCrmTools.WebResourcesManager
    Assembly Version: 1.2016.12.6
    Win32 Version: 1.2016.12.6
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
MsCrmTools.WorkflowExplorer
    Assembly Version: 1.2016.0.3
    Win32 Version: 1.2016.0.3
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMTOOLS.WORKFLOWEXPLORER.DLL
----------------------------------------
MSCRMUtilities.FetchXMLToStringConverter
    Assembly Version: 1.0.0.5
    Win32 Version: 1.0.0.5
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSCRMUTILITIES.FETCHXMLTOSTRINGCONVERTER.DLL
----------------------------------------
MsDyn.Contrib.CloneFieldDefinitions
    Assembly Version: 1.0.24.0
    Win32 Version: 1.0.24
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/MSDYN.CONTRIB.CLONEFIELDDEFINITIONS.DLL
----------------------------------------
RazDynamics.DuplicatesReportForBulkMerge
    Assembly Version: 1.2016.7.17
    Win32 Version: 1.2016.7.17
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/RAZDYNAMICS.DUPLICATESREPORTFORBULKMERGE.DLL
----------------------------------------
RazDynamics.ExceltoCRMBulkAttributeCreator
    Assembly Version: 1.2016.7.17
    Win32 Version: 1.2016.7.17
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/RAZDYNAMICS.EXCELTOCRMBULKATTRIBUTECREATOR.DLL
----------------------------------------
RecordOpener
    Assembly Version: 1.2016.11.12
    Win32 Version: 1.2016.11.12
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/RECORDOPENER.DLL
----------------------------------------
Ryr.ExcelExport
    Assembly Version: 2.4.0.0
    Win32 Version: 2.4.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/RYR.EXCELEXPORT.DLL
----------------------------------------
Ryr.SolutionHistory
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL
----------------------------------------
Ryr.XrmToolBox.EntityImageUpdater
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/RYR.XRMTOOLBOX.ENTITYIMAGEUPDATER.DLL
----------------------------------------
SeAn.XrmToolbox.Plugins.CrmReportSync
    Assembly Version: 2016.8.3.6
    Win32 Version: 2016.8.3.6
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/SEAN.XRMTOOLBOX.PLUGINS.CRMREPORTSYNC.DLL
----------------------------------------
UserTeamSecurityRoleReporter
    Assembly Version: 1.2016.10.2700
    Win32 Version: 1.2016.10.2700
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/USERTEAMSECURITYROLEREPORTER.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration
    Assembly Version: 3.1.1.0
    Win32 Version: 3.1.1.0
    CodeBase: file:///D:/XRM%20TOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 8.0.0.0
    Win32 Version: 8.1.0.359
    CodeBase: file:///D:/XRM%20Toolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
MetadataViewProxies_a8e92f83-1891-469c-a51f-0d0013dc5203
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
NuGet.Core
    Assembly Version: 2.11.1.812
    Win32 Version: 2.11.1.812
    CodeBase: file:///D:/XRM%20Toolbox/NuGet.Core.DLL
----------------------------------------
System.Data.Services.Client
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.556
    CodeBase: file:///D:/XRM%20Toolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.24.0.0
    Win32 Version: 2.24.30411.1323
    CodeBase: file:///D:/XRM%20Toolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    Assembly Version: 4.0.0.0
    Win32 Version: 14.0.23107.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IdentityModel.Selectors
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------

**Comment by MscrmTools** [comment]
Can you try with latest version of XTB?

**Comment by MscrmTools** [comment]
Waiting for a check, i remove this package version

**Comment by anothersphere** [comment]
Yeah I realise that XRMTB itself has not been updating. Downloaded. Tested. Problem remains.
