### ISSUE TITLE
Sitemap Editor Error - URGENT!

### ISSUE THREAD

**Issue by MscrmTools** [MscrmTools/MscrmTools.SiteMapEditor#6]
@Breitenkamp-DK commented on [Mon Jan 09 2017](https://github.com/MscrmTools/XrmToolBox/issues/547)

I have previously removed the 'Service' section from my sitemap but now I need it again. I receive an error when trying to add default subarea to the sitemap. Please see attached file. What to do?
![2017-01-09_10-29-04](https://cloud.githubusercontent.com/assets/25004132/21762065/02557e28-d657-11e6-8d26-ce31c394f36d.png)

CRM version is: 8.1.0.549
Sitemap editor: 1.2017.1.4

---

@MscrmTools commented on [Mon Jan 09 2017](https://github.com/MscrmTools/XrmToolBox/issues/547#issuecomment-271243320)

What is the CRM organization version?

---

@Breitenkamp-DK commented on [Mon Jan 09 2017](https://github.com/MscrmTools/XrmToolBox/issues/547#issuecomment-271243617)

CRM version is: 8.1.0.549 - CRM Online 2016 update
Sitemap editor: 1.2017.1.4

---

@MscrmTools commented on [Mon Jan 09 2017](https://github.com/MscrmTools/XrmToolBox/issues/547#issuecomment-271244946)

Ok, i will review the program and fix this

---

@Breitenkamp-DK commented on [Mon Jan 09 2017](https://github.com/MscrmTools/XrmToolBox/issues/547#issuecomment-271245082)

excellent, thx

**Comment by Breitenkamp-DK** [comment]
I can confirm it is working - thanks for your very fast reply and fix :-)
