### ISSUE TITLE
SiteMap Editor 1.2017.1.3 cannot load sitemap...

### ISSUE THREAD

**Issue by spinifexwem** [MscrmTools/MscrmTools.SiteMapEditor#7]
When I choose Load SiteMap from menu, I get the following error;

Could not load file or assembly 'McTools.Xrm.Connection,Version=1.2017.2.12, Culture=neutral, PublicKeyToken=96037217801d9658' or one of its dependencies.  The system cannot find the file specified.

**Comment by MscrmTools** [comment]
What is your version of XrmToolBox?

**Comment by spinifexwem** [comment]
XrmToolBox version is v1.2016.10.2

**Comment by MscrmTools** [comment]
Please update manually to latest version (your version has a. If that prevents it to  find updates and use autoupdate)
Then update SiteMapEditor to latest version too

**Comment by spinifexwem** [comment]
Thanks issue resolved.  Manually upgraded to latest version of XrmToolBox v1.2017.2.13

Thanks for your help 👍
