### ISSUE TITLE
Not able to load sitemap - newest version of Sitemap Editor

### ISSUE THREAD

**Issue by katy987** [MscrmTools/MscrmTools.SiteMapEditor#8]
Hi,
today I downloaded the latest version Sitemap Editor and when I click on "Load Sitemap" button, the following error messages are displayed:
Either
![image](https://cloud.githubusercontent.com/assets/26740027/24403480/6176e650-13bd-11e7-80d7-b0d990d16dff.png)

or 

![image](https://cloud.githubusercontent.com/assets/26740027/24403537/a97b9b8a-13bd-11e7-943e-a3fdb2b2028c.png)

Before the update, 10 minutes before the update, it worked. 
Could you please advise me what to do? I really need this tool.

Thnx.

**Comment by MscrmTools** [comment]
What is your version of XrmToolBox and CRM?

**Comment by katy987** [comment]
XrmToolBox is version 1.2017.2.13 and CRM is Dynamics 365.

**Comment by MscrmTools** [comment]
Update is available in Plugins Store

**Comment by katy987** [comment]
Perfect, thanks a lot :)
