### ISSUE TITLE
Getting validation errors after editing 

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/MscrmTools.SiteMapEditor#9]
VERY IMPORTANT UPFRONT NOTE - I *cannot* yet confirm that this is a bug with the site map editor editing 8.2 sitemaps- I'm still working to update my sitemap.

After updating the sitemap (as I have hundreds of times with previous versions) I started getting occasional errors opening areas in CRM - I tested the CRM Sitemap editor and I get this validation error: 
_"Sitemap xml failed XSD validation with the following error: 'The element 'SiteMap' has invalid child element 'parsererror' in namespace 'http://www.w3.org/1999/xhtml'. List of possible elements expected: 'Area'.' at line 1 position 39."_ 

Additionally when I open the sitemap editor - I see multiple (3) 'default' sitemaps. - 
Any thoughts on whether the two are related or if there's a good way to figure out why my sitemap is at least partially corrupt?

**Comment by MscrmTools** [comment]
Hi Scott, 

Can you load the sitemaps with SiteMapEditor, display their XML and send them to me?

**Comment by mscottsewell** [comment]
sent. -

**Comment by MscrmTools** [comment]
Ok, so the SiteMap are ok but it seems that the validation fails because of "white space" character interpreted as a child element... weird...

**Comment by MscrmTools** [comment]
I'm not sure I understood, where did you get this validation error message? from within CRM or SiteMapEditor?

**Comment by mscottsewell** [comment]
The validation error occurred inside the CRM sitemap editor after having edited it in the xrmtoolbox sitemapeditor.

Also - why are there 3 versions of the 'default' shown?

**Comment by MscrmTools** [comment]
Default is set by the tool when there is no name for an app... maybe there is multiple stage for an app (draft, validated, published). I need to investigate further

**Comment by mscottsewell** [comment]
New info - I just reproduced the error above (Sitemap xml failed XSD validation) on a new instance after installing field services - without editing using the toolbox.  I'm opening a ticket with Microsoft.
(the multiple 'default' sitemaps are still odd.)

**Comment by MscrmTools** [comment]
Ok, thank for the info! I will open a trial with field services too to check the list of sitemaps

**Comment by mscottsewell** [comment]
BTW it's field services /plus/ Iot for Field services. - I should have been more specific. :)

**Comment by jukkan** [comment]
I also saw the multiple Default sitemaps issue in one environment now. There's one custom App created there, which shows with its own name in the Sitemap Selection dialog as expected. Then there are 5 items named "Default". Interestingly enough, 4 of these point to the App's sitemap and only one (the last one on the list) leads to the actual default sitemap of the instance. I didn't encounter any issues with the actual sitemap contents editing, so this looks like just a UI issue luckily.

**Comment by MscrmTools** [comment]
OK, I found out what was the problem with multiples Default items. A fix is on its way
